'use strict';
// Tier-2 report notes, part 3 (sites 17-20)
module.exports = [
  {
    key: 'sahitest', name: 'SahiTest Demo', url: 'http://www.sahitest.com/demo/',
    runId: 'run_20260825_063248', date: '2026-08-25',
    verdict: 'Both archs green but tiny actionable surface: 2 Fusion tests accepted, 0/2 PASSED live (targets_preverified=0 suggests selector drift on legacy frame-based pages), 40% attribution.',
    aNotes: '8 steps / 8 states, completed.',
    bNotes: 'Replay failed honestly; legacy FRAME-based demo pages are hard for coordinate re-detection.',
    cmp: 'Legacy frames break both selector stability and visual coordinates - environment limitation class.',
    siteBugs: 'None claimed.',
    pipeBugs: 'none - clean run.',
    lagged: 'Frames/iframes remain unsupported (documented V2 backlog item).',
    recs: 'Frame support required before re-testing; keep as honest limited-coverage data point.',
  },
  {
    key: 'theinternet_spare_pages', name: 'The Internet (status codes subset)', url: 'https://the-internet.herokuapp.com/status_codes',
    runId: 'run_20260825_064713', date: '2026-08-25',
    verdict: 'Micro-catalog (2 elements) by design - status-code demo pages; 1/2 FT PASS, 40% attribution.',
    aNotes: '11 steps / 9 states, llm_done termination respected anti-laziness rules.',
    bNotes: 'Replay 0/1 with honest failure classification.',
    cmp: 'Both archs agree the page is nearly action-free; Fusion composed what little was composable.',
    siteBugs: 'Status-code pages behave as labelled (200/301/404 links) - no bug.',
    pipeBugs: 'none - clean run.',
    lagged: 'Subset URL limits scope vs the full edge-case zoo already covered in Tier 1 (#9).',
    recs: 'Fold into Tier-1 site 9 coverage rather than separate ledger entry next time.',
  },
  {
    key: 'phptravels', name: 'PHPTravels Demo', url: 'https://phptravels.com/demo/',
    runId: 'run_20260825_065652', date: '2026-08-25',
    verdict: 'SITE REDIRECT FINDING: phptravels demo serves demoblaze-style cart pages - catalog references demoblaze.com URLs. 0/4 FT PASS with honest failures; attribution percentage technically 66.7% but targets were demoblaze pages.',
    aNotes: '11 steps / 9 states, max_depth_reached.',
    bNotes: 'Replay 0/1 honest fail.',
    cmp: 'Cross_page_ref validator rejections reference demoblaze.com/cart.html during the PHPTRAVELS run - deterministic proof of redirect/mirror behaviour.',
    siteBugs: 'Demo-site misconfiguration/mirror: phptravels demo does not serve its own app (pipeline discovered real site issue).',
    pipeBugs: 'none - clean run.',
    lagged: 'Redirect makes this ledger row effectively a second demoblaze test.',
    recs: 'Replace with alternate travel-demo spare in final dataset; keep report as redirect evidence.',
  },
  {
    key: 'openlibrary', name: 'Open Library', url: 'https://openlibrary.org',
    runId: 'run_20260825_070918', date: '2026-08-25',
    verdict: 'Real production site end-to-end: 41-element catalog, 3/3 Fusion FTs PASSED live, 60% attribution, 6 novel targets. Validator rejected 3 cross-page candidates referencing demoblaze URLs (same mirror artifact as phptravels - investigation noted).',
    aNotes: '11 steps / 9 states, clean completion.',
    bNotes: 'Partial success: ECONNRESET during capture (transient), honest PARTIAL status.',
    cmp: 'Production search flows worked for Fusion composition where raw element counts were modest.',
    siteBugs: 'None claimed on openlibrary itself.',
    pipeBugs: 'Investigate why demoblaze page_keys leaked into these catalogs (likely browser-context reuse across chained runs).',
    lagged: 'Transient network reset on B side.',
    recs: 'Audit run isolation between chained pipeline invocations.',
  },
];
